[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-vvx"

[tool.black]
line-length = "88"

[tool.poetry.group.dev.dependencies]
black = "^24.2.0"
flake8 = "^7.0.0"
flake8-black = "^0.3.6"
flake8-docstrings = "^1.7.0"
flake8-isort = "^6.1.1"
ipython = "^8.22.2"
isort = "^5.12.0"
neovim = "^0.3.1"
pdbpp = "^0.10.3"
pycodestyle = "^2.11.1"
pylama = "^8.4.1"
pylint = "^2.17.4"
pytest = "^8.1.1"

[build-system]
