#!/usr/bin/env python

"""Install development dependencies."""

import json
from pathlib import Path
from subprocess import run
from sys import argv


def main(configdir):
    """Do the thing."""
    path = Path(configdir, "dependencies.json")

    with open(path) as fp:
        data = json.load(fp)

    for pkg in data.get("dev", []):
        run([
            "poetry",
            "add",
            "--group",
            "dev",
            f"{pkg}==*"
        ])


if __name__ == "__main__":
    main(argv[1:])
